name = "nogaritics"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "d56bbb3bb83741aba3ba69ef4884834f"

[vars]
AUTH_URL = "https://www.ngritics.com"
